language: python

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -y --fix-missing libzbar-dev libdmtx0a;
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -f inselect.yml
  - source activate inselect

install:
  - pip install -r requirements.pip
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - pyrcc5 icons.qrc > inselect/gui/icons.py

script:
  - nosetests --verbose --with-coverage --cover-inclusive --cover-tests --cover-package=inselect --verbose inselect

after_success:
  - coveralls
